### ISSUE TITLE
Class not found DatatypeFactory

### ISSUE THREAD

**Issue by himion0** [satyan/sugar#626]
Getting this error when trying to use the library in a fragment:

```
 java.lang.ClassNotFoundException: Didn't find class "org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl" on path: DexPathList[[zip file "/data/app/net.ddns.himion0.yoke-1/base.apk"],nativeLibraryDirectories=[/data/app/net.ddns.himion0.yoke-1/lib/arm64, /vendor/lib64, /system/lib64]]
... 27 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

This inside the main Activity after the `SugarContext.init(getApplicationContext())` is called

`java.lang.NoSuchFieldException: No field mFlags in class Landroid/service/media/MediaBrowserService$Result; (declaration of 'android.service.media.MediaBrowserService$Result' appears in /system/framework/framework.jar:classes2.dex)`

**Comment by filipHypercube** [comment]
I got the same error a few hours ago - solved it by updating version of sugar to 1.5 from 1.4 - Multidex was not working in 1.4. It might be the case here too...

**Comment by himion0** [comment]
I tried adding:

` compile 'com.github.satyan:sugar:1.5'` 

to the build.gradle file however I coudn't get it to run

**Comment by himion0** [comment]
Confirmed worki
