### ISSUE TITLE
sugar java.lang.NoSuchMethodError: No static method updateInTx, save, etc after upgrading to 1.5

### ISSUE THREAD

**Issue by Pascal66** [satyan/sugar#756]

**Comment by Pascal66** [comment]
added super() in constructor ?, only save work, not update with extending pojos
investigate more
